name: Download and Cache Packages

on:
 workflow_dispatch:

jobs:
  download_and_cache_packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Download cached packages artifact
      #  uses: actions/download-artifact@v2
       # with:
         # name: cached-packages
         # path: cached_packages

      - name: Download packages if not cached
        id: download_packages
        run: |
         if [ ! -f "cached_packages/package1.zip" ] || [ ! -f "cached_packages/package2.zip" ]; then
            echo "Downloading packages..."
            curl -o file1 https://github.com/actions/actions-runner-controller/discussions/2174
            curl -o file2 https://igorzhivilo.com/github-actions/github-actions-automatic-scaling
            mkdir -p cached_packages
            mv file1 cached_packages/
            mv file2 cached_packages/

            # Indicate that downloads occurred in this run
            echo "::set-output name=downloads-run::true"
          else
            # Indicate that downloads did not occur in this run
            echo "::set-output name=downloads-run::false"
          fi

      - name: Upload cached packages as artifacts
        if: steps.download_packages.outputs.downloads-run == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: cached-packages
          path: cached_packages
