name: Hybris Package Download Workflow

on:
 workflow_dispatch:

jobs:
  download_pkgs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Download Hybris Installables
        id: download_pkgs
        continue-on-error: false
        run: |
          echo "Downloading packages"
           curl -O https://github.com/marketplace/actions/nested-github-runners-action


      - name: Cache downloaded packages
        uses: actions/cache@v2
        with:
          path: |
            hybrisServer-Platform.zip
            ahybrisServer-AllExtensions.zip
            jacoco.tgz
          key: ${{ runner.os }}-pkgs-${{ hashFiles('**/hybrisServer-Platform.zip') }}-${{ hashFiles('**/ahybrisServer-AllExtensions.zip') }}-${{ hashFiles('**/jacoco.tgz') }}

     
