name: quality

on:
  workflow_dispatch:

jobs:
  download_and_cache_packages:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache downloaded packages
        id: dca 
        uses: actions/cache@v2
        with:
          path: cached_packages
          key: ${{ runner.os }}-${{ hashFiles('cached_packages/**') }}

      - name: Download packages if not cached
        if: steps.dca.outputs.cache-hit != 'true'
        run: |
          echo "Downloading packages..."
          curl -o file1 https://github.com/actions/actions-runner-controller/discussions/2174
          curl -o file2 https://igorzhivilo.com/github-actions/github-actions-automatic-scaling
          mkdir -p cached_packages
          mv file1 cached_packages/
          mv file2 cached_packages/
