name: main
on: 
  push: { branches: [main] }

jobs:
  get-runner:
    if: ${{ always() }}
    runs-on: custom-runner
    outputs:
      RUNNER: ${{ runner.name }}
    steps:
      - run: echo "selected runner = ${{ runner.name }}"

  other-job:
    name: another job
    needs: get-runner
    runs-on: ${{needs.get-runner.outputs.RUNNER}}
    steps:
      - run: echo "done"
