name: same
on: 
  workflow_dispatch

jobs:
  get-runner:
    runs-on: self-hosted
    outputs:
      matrix: ${{ toJson([{'runner_label': runner.label}]) }}
    steps:
      - name: Echo Runner Label
        run: echo "::set-output name=runner_label::${{ runner.label }}"

  other-job:
    name: another job
    needs: get-runner
    runs-on: self-hosted
    strategy:
      matrix:
        runner_label: ${{fromJson(needs.get-runner.outputs.matrix)}}
    steps:
      - name: Run on Specified Runner
        run: echo "Running on runner with label ${{ matrix.runner_label }}"
