name: same
on: 
  workflow_dispatch

jobs:
  get-runner:
    runs-on: self-hosted
    outputs:
      runner_label: ${{ steps.set-label.outputs.runner_label }}
    steps:
      - name: Set Runner Label
        id: set-label
        run: echo "::set-output name=runner_label::${{ runner.label }}"

  other-job:
    name: another job
    needs: get-runner
    runs-on: self-hosted
    env:
      RUNNER_LABEL: ${{ needs.get-runner.outputs.runner_label }}
    steps:
      - name: Run on Specified Runner
        run: echo "Running on runner with label $RUNNER_LABEL"
