name: same
on: 
  workflow_dispatch

jobs:
  get-runner:
    runs-on: self-hosted
    outputs:
      RUNNER: ${{ steps.get-runner-output.outputs.RUNNER_LABEL }}
    steps:
      - name: Get runner info
        id: get-runner-output
        run: echo "::set-output name=RUNNER::${{ runner.name }}"

  other-job:
    name: another job
    needs: get-runner
    runs-on: ${{needs.get-runner.outputs.RUNNER_LABEL}}
    steps:
      - run: echo "same runner"
